create table
  public.cinema (
    id bigint generated by default as identity not null,
    name character varying null,
    constraint cinemas_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.discount (
    id bigint generated by default as identity not null,
    title character varying null,
    discount numeric null,
    cinema_id bigint null,
    discount_type public.membership_discount_types null default 'none'::membership_discount_types,
    constraint memberships_pkey primary key (id),
    constraint memberships_cinema_id_fkey foreign key (cinema_id) references cinema (id)
  ) tablespace pg_default;

  create table
  public.membership (
    id bigint generated by default as identity not null,
    title public.membership_name null,
    cinema_id bigint null,
    discount_type public.membership_discount_types null,
    constraint membership_pkey1 primary key (id),
    constraint membership_cinema_id_fkey1 foreign key (cinema_id) references cinema (id) on update cascade on delete cascade
  ) tablespace pg_default;

  create table
  public.user_data (
    auth_uuid uuid not null,
    username character varying null,
    first_name character varying null,
    last_name character varying null,
    birth_date date null,
    constraint user_data_pkey primary key (auth_uuid),
    constraint user_data_auth_uuid_fkey foreign key (auth_uuid) references auth.users (id)
  ) tablespace pg_default;

  create table
  public.user_membership (
    id bigint generated by default as identity not null,
    user_id uuid null,
    membership_id bigint null,
    bought_tickets bigint null default '0'::bigint,
    constraint membership_pkey primary key (id),
    constraint membership_user_id_fkey foreign key (user_id) references user_data (auth_uuid) on update cascade on delete cascade,
    constraint user_membership_membership_id_fkey foreign key (membership_id) references membership (id)
  ) tablespace pg_default;